/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TADKPBIMBEL;

import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class Bimbelmainview extends javax.swing.JFrame {
    int modul, privat, group, matkul1, matkul2, matkul3, harga, hargatot;

    /**
     * Creates new form Bimbelmainview
     */
    public Bimbelmainview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        bodypanel = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        btnproduk = new javax.swing.JButton();
        btnttg = new javax.swing.JButton();
        btnbyr = new javax.swing.JButton();
        btnext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        produkpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnplj1 = new javax.swing.JButton();
        btnplj2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        pembayaranpanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Pilihanmatkul1 = new javax.swing.JComboBox<>();
        Pilihanmatkul2 = new javax.swing.JComboBox<>();
        Pilihanmatkul3 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        Textnama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Textout = new javax.swing.JTextArea();
        btnpesan = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnbayar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Textid = new javax.swing.JTextField();
        Modulpembe = new javax.swing.JComboBox<>();

        jPanel7.setBackground(new java.awt.Color(56, 125, 116));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("bimbeltekkom");
        setPreferredSize(new java.awt.Dimension(1292, 703));

        bodypanel.setBackground(new java.awt.Color(255, 255, 255));

        sidepanel.setBackground(new java.awt.Color(56, 125, 116));

        btnproduk.setBackground(new java.awt.Color(255, 255, 255));
        btnproduk.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Downloads\\leaflet (2).png")); // NOI18N
        btnproduk.setText("Produk");
        btnproduk.setIconTextGap(10);
        btnproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprodukActionPerformed(evt);
            }
        });

        btnttg.setBackground(new java.awt.Color(255, 255, 255));
        btnttg.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Downloads\\information.png")); // NOI18N
        btnttg.setText("Tentang");
        btnttg.setIconTextGap(10);
        btnttg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnttgActionPerformed(evt);
            }
        });

        btnbyr.setBackground(new java.awt.Color(255, 255, 255));
        btnbyr.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Downloads\\wallet.png")); // NOI18N
        btnbyr.setText("Pembayaran");
        btnbyr.setIconTextGap(10);
        btnbyr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbyrActionPerformed(evt);
            }
        });

        btnext.setBackground(new java.awt.Color(255, 255, 255));
        btnext.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Downloads\\on-off-button.png")); // NOI18N
        btnext.setText("Keluar");
        btnext.setIconTextGap(10);
        btnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnextActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Downloads\\monitor (2).png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIMBTEK");

        jLabel7.setText("Kami ada untukmu");

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnproduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnttg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnbyr, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(44, 44, 44))))))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(85, 85, 85)
                .addComponent(btnproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnbyr, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnttg, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainpanel.setBackground(new java.awt.Color(149, 165, 166));
        mainpanel.setLayout(new java.awt.CardLayout());

        produkpanel.setBackground(new java.awt.Color(247, 246, 231));
        produkpanel.setPreferredSize(new java.awt.Dimension(1292, 703));

        jPanel2.setBackground(new java.awt.Color(66, 70, 66));

        jLabel3.setBackground(new java.awt.Color(247, 246, 231));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 246, 231));
        jLabel3.setText("PRODUK");

        jLabel4.setBackground(new java.awt.Color(247, 246, 231));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 246, 231));
        jLabel4.setText("Pilih layanan sesuai kebutuhanmu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)))
                .addContainerGap(1218, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        btnplj1.setText("Pelajari lebih lanjut");
        btnplj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplj1ActionPerformed(evt);
            }
        });

        btnplj2.setText("Pelajari lebih lanjut");
        btnplj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplj2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(34, 40, 49));
        jPanel3.setPreferredSize(new java.awt.Dimension(175, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(56, 125, 116));
        jPanel8.setPreferredSize(new java.awt.Dimension(175, 177));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Downloads\\user-group.png")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(247, 246, 231));
        jLabel11.setText("Group");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11))
                    .addComponent(jLabel9))
                .addGap(54, 54, 54))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(56, 125, 116));
        jPanel9.setPreferredSize(new java.awt.Dimension(175, 177));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Downloads\\man-user.png")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(247, 246, 231));
        jLabel12.setText("Private");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12))
                    .addComponent(jLabel8))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(27, 27, 27))
        );

        jPanel10.setBackground(new java.awt.Color(34, 40, 49));
        jPanel10.setPreferredSize(new java.awt.Dimension(175, 25));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout produkpanelLayout = new javax.swing.GroupLayout(produkpanel);
        produkpanel.setLayout(produkpanelLayout);
        produkpanelLayout.setHorizontalGroup(
            produkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produkpanelLayout.createSequentialGroup()
                .addGroup(produkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(produkpanelLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(produkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnplj1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(288, 288, 288)
                        .addGroup(produkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(produkpanelLayout.createSequentialGroup()
                                .addComponent(btnplj2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(415, 415, 415)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(produkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(produkpanelLayout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1248, Short.MAX_VALUE)))
        );
        produkpanelLayout.setVerticalGroup(
            produkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produkpanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(produkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(produkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(produkpanelLayout.createSequentialGroup()
                        .addGroup(produkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(produkpanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(produkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnplj1)
                            .addComponent(btnplj2)))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
            .addGroup(produkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produkpanelLayout.createSequentialGroup()
                    .addContainerGap(295, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(227, 227, 227)))
        );

        mainpanel.add(produkpanel, "card2");

        pembayaranpanel.setBackground(new java.awt.Color(247, 246, 231));

        jPanel6.setBackground(new java.awt.Color(66, 70, 66));

        jLabel5.setBackground(new java.awt.Color(247, 246, 231));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 246, 231));
        jLabel5.setText("PEMBAYARAN");

        jLabel6.setBackground(new java.awt.Color(247, 246, 231));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 246, 231));
        jLabel6.setText("Selesaikan pembayaran untuk menikmati layanan kami");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)))
                .addContainerGap(1218, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Detail Pesanan");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Model pembelajaran");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Mata kuliah 1");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Mata kuliah 2");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Mata Kuliah 3");

        Pilihanmatkul1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Matkul 1", "Fisika dasar 1", "Kalkulus", "Matematika Teknik", "Algoritma", "Praktikum Dkp" }));
        Pilihanmatkul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihanmatkul1ActionPerformed(evt);
            }
        });

        Pilihanmatkul2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Matkul 2", "Fisika dasar 1", "Kalkulus", "Matematika Teknik", "Algoritma", "Praktikum Dkp" }));
        Pilihanmatkul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihanmatkul2ActionPerformed(evt);
            }
        });

        Pilihanmatkul3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Matkul 3", "Fisika dasar 1", "Kalkulus", "Matematika Teknik", "Algoritma", "Praktikum Dkp" }));
        Pilihanmatkul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihanmatkul3ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Nama Pemesan");

        Textnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextnamaActionPerformed(evt);
            }
        });

        Textout.setColumns(20);
        Textout.setRows(5);
        jScrollPane1.setViewportView(Textout);

        btnpesan.setText("Pesan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnbayar.setText("Bayar");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Id line");

        Textid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextidActionPerformed(evt);
            }
        });

        Modulpembe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pembelajaran", "Privat", "Group" }));
        Modulpembe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModulpembeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pembayaranpanelLayout = new javax.swing.GroupLayout(pembayaranpanel);
        pembayaranpanel.setLayout(pembayaranpanelLayout);
        pembayaranpanelLayout.setHorizontalGroup(
            pembayaranpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pembayaranpanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pembayaranpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pembayaranpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pembayaranpanelLayout.createSequentialGroup()
                        .addGroup(pembayaranpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(Pilihanmatkul3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Pilihanmatkul2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Pilihanmatkul1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Textnama)
                            .addComponent(jLabel14)
                            .addComponent(Modulpembe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Textid, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(pembayaranpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pembayaranpanelLayout.createSequentialGroup()
                                .addComponent(btnpesan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel16)
                    .addGroup(pembayaranpanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pembayaranpanelLayout.setVerticalGroup(
            pembayaranpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pembayaranpanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pembayaranpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pembayaranpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pembayaranpanelLayout.createSequentialGroup()
                        .addGroup(pembayaranpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Textnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Textid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Modulpembe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel14)
                        .addGap(22, 22, 22)
                        .addComponent(Pilihanmatkul1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pilihanmatkul2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(13, 13, 13)
                .addGroup(pembayaranpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pilihanmatkul3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnpesan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbayar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnclear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );

        mainpanel.add(pembayaranpanel, "card3");

        javax.swing.GroupLayout bodypanelLayout = new javax.swing.GroupLayout(bodypanel);
        bodypanel.setLayout(bodypanelLayout);
        bodypanelLayout.setHorizontalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodypanelLayout.setVerticalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprodukActionPerformed
        // TODO add your handling code here:
        // gantipanel:
        mainpanel.removeAll();
        mainpanel.revalidate();
        mainpanel.repaint();
        
        //panel:
        mainpanel.add(produkpanel);
        mainpanel.revalidate();
        mainpanel.repaint();
    }//GEN-LAST:event_btnprodukActionPerformed

    private void btnplj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplj2ActionPerformed
        // TODO add your handling code here:
        grup g = new grup();
        g.setVisible(true);
    }//GEN-LAST:event_btnplj2ActionPerformed

    private void btnttgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnttgActionPerformed
        // TODO add your handling code here:
        
        Popupabout n = new Popupabout();
        n.setVisible(true);
    }//GEN-LAST:event_btnttgActionPerformed

    private void btnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnextActionPerformed
        // TODO add your handling code here:
        int dialogbtn;
        dialogbtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah anda yakin?", "Peringatan", dialogbtn);
        
        if (dialogResult==0){
            System.exit(0);
        } else {
            
        }
            
    }//GEN-LAST:event_btnextActionPerformed

    private void btnbyrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbyrActionPerformed
        // TODO add your handling code here:
        //ganti panel:
        mainpanel.removeAll();
        mainpanel.revalidate();
        mainpanel.repaint();
        
        //panel:
        mainpanel.add(pembayaranpanel);
        mainpanel.revalidate();
        mainpanel.repaint();
    }//GEN-LAST:event_btnbyrActionPerformed

    private void btnplj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplj1ActionPerformed
        // TODO add your handling code here:
        solo s = new solo();
        s.setVisible(true);
    }//GEN-LAST:event_btnplj1ActionPerformed

    private void TextnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextnamaActionPerformed

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        // TODO add your handling code here:
        Textout.setText(
                "Model Pembelajaran: " + Modulpembe.getSelectedItem() +"\n"+
                "Mata Kuliah 1: " + Pilihanmatkul1.getSelectedItem() + " Harga: " + matkul1 +"\n"+
                "Mata Kuliah 2: " + Pilihanmatkul2.getSelectedItem() + " Harga: " + matkul2 +"\n"+
                "Mata Kuliah 3: " + Pilihanmatkul3.getSelectedItem() + " Harga: " + matkul3 +"\n"+
                "Total: " + (modul+matkul1+matkul2+matkul3));
    }//GEN-LAST:event_btnpesanActionPerformed

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        // TODO add your handling code here:
           int dialogbtn;
        dialogbtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah anda yakin?", "Peringatan", dialogbtn);
        
        if (dialogResult==0){
            Textout.setText("Pembayaran berhasil " +"\n"+
                    Textnama.getText() + " Selanjutnya akan kami hubungi anda melalui line");
        } else {
            
        }
            
    }//GEN-LAST:event_btnbayarActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        Textnama.setText("");
        Textid.setText("");
        Modulpembe.setSelectedItem("Pilih Pembelajaran");
        Pilihanmatkul1.setSelectedItem("Pilih Matkul 1");
        Pilihanmatkul2.setSelectedItem("Pilih Matkul 2");
        Pilihanmatkul3.setSelectedItem("Pilih Matkul 3");
        Textout.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void TextidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextidActionPerformed

    private void ModulpembeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModulpembeActionPerformed
        // TODO add your handling code here:
        if (Modulpembe.getSelectedItem().equals("Pilih Pembelajaran")){
            modul = 0;
        }
        else if (Modulpembe.getSelectedItem().equals("Privat")){
            modul = 100000;
        }
        else if (Modulpembe.getSelectedItem().equals("Group")){
            modul = 50000;
        }
                
    }//GEN-LAST:event_ModulpembeActionPerformed

    private void Pilihanmatkul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pilihanmatkul1ActionPerformed
        // TODO add your handling code here:
        if (Pilihanmatkul1.getSelectedItem().equals("pilih matkul 1")){
            matkul1 = 0;
        }
        else if(Pilihanmatkul1.getSelectedItem().equals("Fisika dasar 1")){
            matkul1 = 20000;
        }
        else if(Pilihanmatkul1.getSelectedItem().equals("Kalkulus")){
            matkul1 = 20000;
        }
        else if (Pilihanmatkul1.getSelectedItem().equals("Matematika Teknik")){
            matkul1 = 25000;
        } 
        else if (Pilihanmatkul1.getSelectedItem().equals("Algoritma")){
            matkul1 = 22000;
        }
    }//GEN-LAST:event_Pilihanmatkul1ActionPerformed

    private void Pilihanmatkul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pilihanmatkul2ActionPerformed
        // TODO add your handling code here:
        if (Pilihanmatkul2.getSelectedItem().equals("pilih matkul 2")){
            matkul2 = 0;
        }
        else if(Pilihanmatkul2.getSelectedItem().equals("Fisika dasar 1")){
            matkul2 = 20000;
        }
        else if(Pilihanmatkul2.getSelectedItem().equals("Kalkulus")){
            matkul2 = 20000;
        }
        else if (Pilihanmatkul2.getSelectedItem().equals("Matematika Teknik")){
            matkul2 = 25000;
        } 
        else if (Pilihanmatkul2.getSelectedItem().equals("Algoritma")){
            matkul2 = 22000;
        }
    }//GEN-LAST:event_Pilihanmatkul2ActionPerformed

    private void Pilihanmatkul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pilihanmatkul3ActionPerformed
        // TODO add your handling code here:
        if (Pilihanmatkul3.getSelectedItem().equals("pilih matkul 3")){
            matkul3 = 0;
        }
        else if(Pilihanmatkul3.getSelectedItem().equals("Fisika dasar 1")){
            matkul3 = 20000;
        }
        else if(Pilihanmatkul3.getSelectedItem().equals("Kalkulus")){
            matkul3 = 20000;
        }
        else if (Pilihanmatkul3.getSelectedItem().equals("Matematika Teknik")){
            matkul3 = 25000;
        } 
        else if (Pilihanmatkul3.getSelectedItem().equals("Algoritma")){
            matkul3 = 22000;
        }
    }//GEN-LAST:event_Pilihanmatkul3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bimbelmainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bimbelmainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bimbelmainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bimbelmainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bimbelmainview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Modulpembe;
    private javax.swing.JComboBox<String> Pilihanmatkul1;
    private javax.swing.JComboBox<String> Pilihanmatkul2;
    private javax.swing.JComboBox<String> Pilihanmatkul3;
    private javax.swing.JTextField Textid;
    private javax.swing.JTextField Textnama;
    private javax.swing.JTextArea Textout;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JButton btnbayar;
    private javax.swing.JButton btnbyr;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnext;
    private javax.swing.JButton btnpesan;
    private javax.swing.JButton btnplj1;
    private javax.swing.JButton btnplj2;
    private javax.swing.JButton btnproduk;
    private javax.swing.JButton btnttg;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel pembayaranpanel;
    private javax.swing.JPanel produkpanel;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables


}
